language: node_js
node_js:
  - "10.22.0"

before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/energywebfoundation/passport-did-auth.git" > /dev/null 2>&1
  - git reset --hard
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git fetch origin master:master
  - git fetch origin develop:develop

install:
  - npm install

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    script: "npx semantic-release"
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: "npx semantic-release"
    skip_cleanup: true
    on:
      branch: master
