name: Lint source code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.17.0'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npx eslint --output-file eslint_report.json --format json lib test
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        if: always()
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'
      - name: Run Prettier
        run: npx prettier --check lib/**/*.*s test/**/*.*s
