name: Deploy

on:
  push:
    branches: [ 'develop', 'master' ]
  pull_request:
    branches: [ 'develop', 'master' ]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14.17.0'
          registry-url: https://registry.npmjs.org/

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          git remote set-url origin "https://${{ secrets.GH_ACTION_TOKEN }}@github.com/energywebfoundation/passport-did-auth.git" > /dev/null 2>&1
          git reset --hard
          git fetch -u origin master:master
          git fetch -u origin develop:develop

      - name: Set npm credentials
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install package
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Eslint validation
        run: npm run lint

      - name: Npm Run Test
        run: npm run test

      - name: Deploy on develop branch
        if: github.ref == 'refs/heads/develop'
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy on master branch
        if: github.ref == 'refs/heads/master'
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync_master_to_development_branch :
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.GH_ACTION_TOKEN }}

      - name: Merge master into develop branch
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          git merge origin/master
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
