name: Deploy

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PUSH_TOKEN }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10.0'
          registry-url: https://registry.npmjs.org/

      - name: Set npm credentials
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install package
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Eslint validation
        run: npm run lint

      - name: Npm Run Test
        run: npm run test

      - name: Publish ${{ github.ref }}
        uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync_development_with_master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: deploy
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.GH_PUSH_TOKEN }}
      - name: Merge master into develop branch
        run: |
          git merge origin/master
          git push origin develop
